<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Staff_model extends CI_Model
{

    public $table = 'staff';
    public $id = 'staff_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('staff_id,staff_nama,staff_tplahir,staff_tglahir,staff_jenkel,staff_alamat,staff_email,staff_telpon,reg_id,user_id');
        $this->datatables->from('staff');
        //add this line for join
        //$this->datatables->join('table2', 'staff.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('staff/read/$1'),'Read')." | ".anchor(site_url('staff/update/$1'),'Update')." | ".anchor(site_url('staff/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'staff_id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('staff_id', $q);
    	$this->db->or_like('staff_nama', $q);
    	$this->db->or_like('staff_tplahir', $q);
    	$this->db->or_like('staff_tglahir', $q);
    	$this->db->or_like('staff_jenkel', $q);
    	$this->db->or_like('staff_alamat', $q);
    	$this->db->or_like('staff_email', $q);
    	$this->db->or_like('staff_telpon', $q);
    	$this->db->or_like('reg_id', $q);
    	$this->db->or_like('user_id', $q);
    	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('staff_id', $q);
    	$this->db->or_like('staff_nama', $q);
    	$this->db->or_like('staff_tplahir', $q);
    	$this->db->or_like('staff_tglahir', $q);
    	$this->db->or_like('staff_jenkel', $q);
    	$this->db->or_like('staff_alamat', $q);
    	$this->db->or_like('staff_email', $q);
    	$this->db->or_like('staff_telpon', $q);
    	$this->db->or_like('reg_id', $q);
    	$this->db->or_like('user_id', $q);
    	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Staff_model.php */
/* Location: ./application/models/Staff_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-04-15 05:05:51 */
/* http://harviacode.com */